// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var carousel, displayImage, interval, isRunning, numItems, startCarousel, timerId;
    carousel = this;
    carousel.selectedItem = 0;
    isRunning = false;
    timerId = 0;
    interval = 5000;
    numItems = $(".item").length;
    $(".tools #onOff").click(function() {
      if (isRunning === false) {
        carousel.selectedItem += 1;
        if (carousel.selectedItem === numItems) {
          carousel.selectedItem = 0;
        }
        displayImage(carousel.selectedItem);
        timerId = startCarousel(interval, carousel.selectedItem, numItems);
        return isRunning = true;
      } else {
        clearInterval(timerId);
        return isRunning = false;
      }
    });
    $(".tools #next").click(function() {
      carousel.selectedItem += 1;
      if (carousel.selectedItem === numItems) {
        carousel.selectedItem = 0;
      }
      return displayImage(carousel.selectedItem);
    });
    $("tools #previous").click(function() {
      carousel.selectedItem -= 1;
      if (carousel.selectedItem === 0) {
        carousel.selectedItem = numItems - 1;
      }
      return displayImage(carousel.selectedItem);
    });
    $(".tools #pop").click(function() {
      var docHeight, docWidth, imageHeight, item, popHeight, popWidth;
      clearInterval(timerId);
      isRunning = false;
      docHeight = document.documentElement.clientHeight;
      docWidth = document.documentElement.clientWidth;
      item = $(".selected :first-child").clone();
      imageHeight = (docHeight * 0.7) + "px";
      $("#popContent").append(item);
      item.css({
        "height": imageHeight,
        "width": "auto"
      });
      popHeight = $("#popUp").height;
      popWidth = $("#popUp").width;
      $("#popBackground").css({
        "opacity": "0.7",
        "display": "block"
      });
      $("#popBackground").fadeIn("slow");
      $("#popUp").css({
        "display": "block",
        "height": "auto",
        "width": "auto",
        "top": 10
      });
      return $("#popUp").fadeIn("slow");
    });
    $(".popTools #next").click(function() {
      var docHeight, docWidth, imageHeight, item, popHeight, popWidth;
      $("#popContent").empty();
      $('#carousel .popImage').removeClass('popImage');
      carousel.selectedItem += 1;
      if (carousel.selectedItem === numItems) {
        carousel.selectedItem = 0;
      }
      $("#carousel .item:eq(" + carousel.selectedItem + ")").addClass('popImage');
      item = $(".popImage :first-child").clone();
      docHeight = document.documentElement.clientHeight;
      docWidth = document.documentElement.clientWidth;
      imageHeight = (docHeight * 0.7) + "px";
      item.css({
        "height": imageHeight,
        "width": "auto"
      });
      popHeight = $("#popUp").height;
      popWidth = $("#popUp").width;
      $("#popContent").empty();
      return $("#popContent").append(item);
    });
    $("#popClose").click(function() {
      $("#popContent").empty();
      $("#popBackground").css({
        "display": "none"
      });
      return $("#popUp").css({
        "display": "none"
      });
    });
    startCarousel = function(interval, selectedItem, numItems) {
      return setInterval((function() {
        selectedItem += 1;
        if (selectedItem === numItems) {
          selectedItem = 0;
        }
        carousel.selectedItem = selectedItem;
        return displayImage(selectedItem);
      }), interval);
    };
    return displayImage = function(selectedItem) {
      $(".selected").removeClass("selected");
      return $("#carousel .item:eq(" + selectedItem + ")").addClass("selected");
    };
  });

}).call(this);
